blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index),
    path('tags/<slug:slug>/', views.tags),
    path('<slug:pk>/', views.article, name="article"),
    path('<slug:pk>/like', views.like),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
# from django.urls import path
from django.urls import path, include
from mysite import views
from django.views.decorators.cache import cache_page

# -- for サイトマップ --
from django.contrib.sitemaps.views import sitemap
from config.sitemaps import StaticViewSitemap, BlogSiteMap
sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSiteMap,
}

"""
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <script />
    <url>
        <loc>http://127.0.0.1:8080/</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/langding_mui/</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/blog/1/</loc>
        <lastmod>2024-04-24</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/blog/2/</loc>
        <lastmod>2024-04-24</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/blog/3/</loc>
        <lastmod>2024-04-28</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/blog/4/</loc>
        <lastmod>2024-04-29</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://127.0.0.1:8080/blog/5/</loc>
        <lastmod>2024-04-29</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
</urlset>
"""
# -- for サイトマップ --

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('mysite.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
# from django.urls import path
from django.urls import path, include
from mysite import views
from django.views.decorators.cache import cache_page

app_name = "mysite"

urlpatterns = [
    path('', views.index, name="home"),
    path('langding_mui/', views.langding_mui, name="langding_mui"),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    # path('mypage/', views.mypage),
    path('mypage/', views.MypageView.as_view()),
    # path('contact/', views.contact),
    path('contact/', views.ContactView.as_view()),
    path('pay/', views.PayView.as_view()),
    # view単位 DBキャッシュ
    path('cache_test/', views.cache_test),
    # url単位 DBキャッシュ
    path('cache_test2/', cache_page(10)(views.cache_test2)),
    # templateキャッシュ
    path('cache_test3/', views.cache_test3),

    path('ping/', views.ping),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Tag(models.Model):
    slug = models.CharField(primary_key=True, unique=True, max_length=20)
    name = models.CharField(unique=True, max_length=20)

    def __str__(self) -> str:
        return self.slug

class Article(models.Model):
    title = models.CharField(default="", blank=False, null=False, max_length=30)
    text = models.TextField(default="")
    author = models.CharField(default="", max_length=30)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)
    count = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)

class Comment(models.Model):
    comment = models.TextField(default="", max_length=500)
    created_at = models.DateField(auto_now_add=True)
    """
    ◽️リレーション
    他にも以下のものが存在
    OneToOne     1 : 1
    ForeignKey   1 : 多
    ManyToMany   多 : 多 中間テーブルを挟んで参照できるようになる
    """
    # user(1) : comment(多), user削除されたらcommentは削除
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    # article(1) : comment(多), user削除されたらarticleは削除
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

mysite/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    # アカウントが有効かどうか
    is_active = models.BooleanField(default=True)
    # 管理者なのか
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    # アカウントが有効かどうか
    is_active = models.BooleanField(default=True)
    # 管理者なのか
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


# --- OneToOneFieldを同時に作成 ---
from django.db.models.signals import post_save # saveされた直後
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_one_to_one(sender, **kwargs):
    if kwargs['created']:
        from mysite.models.profile_models import Profile
        Profile.objects.create(user=kwargs['instance'])
# --- OneToOneFieldを同時に作成 ---

mysite/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model
import os

def upload_image_to(instance, filename):
    """
    保存したとき「os.path.join('static', 'img', user_id, filename)」の場合
    static/img/{user_id}/ファイル名でファイルが保存される
    """
    user_id = str(instance.user.id)
    # return os.path.join('static', 'img', user_id, filename)

    # GCSのためstaticは別にいらないので修正
    return os.path.join('img', user_id, filename)

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), unique=True, on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(default="匿名ユーザ", max_length=30)
    zipcode = models.CharField(default="", max_length=8)
    prefecture = models.CharField(default="", max_length=6)
    city = models.CharField(default="", max_length=100)
    address = models.CharField(default="", max_length=200)
    image = models.ImageField(default="", blank=True, upload_to=upload_image_to)

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model
from mysite.models.profile_models import Profile

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()
    fields = ('email',)

    class Meta:
        model = get_user_model()
        fields = ('email',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
            'image',
        )

mysite/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.contrib.auth.views import LoginView
from blog.models import Article
from mysite.forms import UserCreationForm, ProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.core.mail import send_mail
import os

def index(request: HttpRequest) -> HttpResponse:
    ranks = Article.objects.order_by('-count')[:2] # 降順
    articles = Article.objects.all()[:3]
    context = {
        'title': 'Really Site',
        'articles': articles,
        'ranks': ranks
    }
    return render(request, 'mysite/index.html', context)

def langding_mui(request: HttpRequest) -> HttpResponse:
    context = {
    }
    return render(request, 'mysite/landing_mui.html', context)

@login_required
def ping(request):
    from django.contrib.sitemaps import ping_google
    try:
        if request.user.is_admin:
            ping_google()
    except Exception as e:
        print(e)
    return redirect('/')

class Login(LoginView):
    template_name='mysite/auth.html'

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        messages.success(self.request, 'ログイン完了')
        return super().form_valid(form)
    def form_invalid(self, form: AuthenticationForm) -> HttpResponse:
        messages.success(self.request, 'ログインエラー')
        return super().form_invalid(form)

def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.save()
            # ログインさせる
            login(request, user)
            messages.success(request, '登録完了')
            return redirect('/')
    return render(request, 'mysite/auth.html', context)

"""
@login_required
def mypage(request):
    context = {}
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '更新完了しました')
    return render(request, 'mysite/mypage.html', context)
"""

from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

class MypageView(LoginRequiredMixin, View):
    context = {}
    def get(self, request):
        return render(request, 'mysite/mypage.html', self.context)

    def post(self, request):
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '更新完了しました')
        return render(request, 'mysite/mypage.html', self.context)

"""
def contact(request):
    context = {
        'grecaptcha_sitekey': os.environ['GRECAPTCHA_SITEKEY']
    }
    if request.method == 'POST':
        recaptcha_token = request.POST.get('g-recaptcha-response')
        response = grecaptcha_request(recaptcha_token)
        if not response:
            messages.error(request, 'reCAPTCHAに失敗しました')
            return redirect(request, 'mysite/contact.html', context)
        subject = 'お問い合わせがありました'
        message = 'お問い合わせがありました\n名前: {}\nメールアドレス: {}\n内容: {}'.format(
            request.POST.get('name'),
            request.POST.get('email'),
            request.POST.get('content'),
        )
        from_email = os.environ['DEFAULT_EMAIL_FROM']
        recipient_list = [
            os.environ['DEFAULT_EMAIL_FROM']
        ]
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=recipient_list
        )
        messages.success(request, 'お問い合わせしました')
    return render(request, 'mysite/contact.html', context)
"""

class ContactView(View):
    context = {
        'grecaptcha_sitekey': os.environ['GRECAPTCHA_SITEKEY']
    }
    def get(self, request):
        return render(request, 'mysite/contact.html', self.context)
    def post(self, request):
        recaptcha_token = request.POST.get('g-recaptcha-response')
        response = grecaptcha_request(recaptcha_token)
        if not response:
            messages.error(request, 'reCAPTCHAに失敗しました')
            return redirect(request, 'mysite/contact.html', self.context)
        subject = 'お問い合わせがありました'
        message = """お問い合わせがありました\n名前: {}\nメールアドレス: {}\n内容: {}""".format(
            request.POST.get('name'),
            request.POST.get('email'),
            request.POST.get('content'),
        )
        from_email = os.environ['DEFAULT_EMAIL_FROM']
        recipient_list = [
            os.environ['DEFAULT_EMAIL_FROM']
        ]
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=recipient_list
        )
        messages.success(request, 'お問い合わせしました')
        return render(request, 'mysite/contact.html', self.context)

def grecaptcha_request(token):
    from urllib import request, parse
    import json, ssl

    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)

    url = "https://www.google.com/recaptcha/api/siteverify"
    headers = { 'content-type': 'application/x-www-form-urlencoded' }
    data = {
        'secret': os.environ['GRECAPTCHA_SECRETKEY'],
        'response': token,
    }
    data = parse.urlencode(data).encode()
    req = request.Request(
        url,
        method="POST",
        headers=headers,
        data=data,
    )
    f = request.urlopen(req, context=context)
    response = json.loads(f.read())
    f.close()

    print('grecaptcha_request response')
    print(response)
    return response['success']

import payjp

class PayView(View):
    payjp.api_key = os.environ['PAYJP_SECRET_KEY']
    public_key = os.environ['PAYJP_PUBLIC_KEY']
    amount = 1000

    def get(self, request):
        context = {
            'amount': self.amount,
            'public_key': self.public_key,
        }
        return render(request, 'mysite/pay.html', context)

    def post(self, request):
        customer = payjp.Customer.create(
            email='test@pay.jp',
            card=request.POST.get('payjp-token'),
        )
        charge = payjp.Charge.create(
            amount=self.amount,
            currency='jpy',
            customer=customer.id,
            description='支払いテスト',
        )
        context = {
            'amount': self.amount,
            'public_key': self.public_key,
            'charge': charge,
        }
        return render(request, 'mysite/pay.html', context)

from django.views.decorators.cache import cache_page

# view単位でキャッシュ (10秒はキャッシュされる, ユーザによって決まっているページに使用)
@cache_page(10)
def cache_test(request):
    context = {
        'answer': prime_factorize(9867280421310721)
    }
    return render(request, 'mysite/cache_test.html', context)

# url単位でキャッシュ
def cache_test2(request):
    context = {
        'answer': prime_factorize(9867280421310721)
    }
    return render(request, 'mysite/cache_test.html', context)

# templateキャッシュ
def cache_test3(request):
    import datetime
    context = {
        'time': datetime.datetime.now().isoformat(),
        'name': request.GET.get('name', None)
    }
    return render(request, 'mysite/cache_test_template.html', context)

def prime_factorize(n):
    a = []
    while n % 2 == 0:
        a.append(2)
        n //= 2
    f = 3
    while f * f <= n:
        if n % f == 0:
            a.append(f)
            n //= f
        else:
            f += 2
    if n != 1:
        a.append(n)
    return a

templates/mysite/auth.html
{% extends 'mysite/base_auth.html' %}

{% block content %}
<div class="container ">
    <div class="row">
        <div class="col-lg-3 m-auto ">
            <h1 class="display-4 font-italic text-center "><a href="/" class="text-decoration-none">ReallySite</a></h1>
        </div>
        <div class="col-lg-3 m-auto ">
            {% if user.is_authenticated %}
            ログイン中です
            {% else %}
            未ログインです
            {% endif %}

            <form class="form-signin mx-4" method="POST">
                {% csrf_token %}
                <div class="text-center">
                    <h1 class="h5 my-4 ">
                        {% if 'login' in request.path %}
                        ログイン
                        {% elif 'signup' in request.path %}
                        新規登録
                        {% endif %}
                    </h1>
                </div>
                <div class="form-label-group my-3">
                    <input type="email" id="id_email" name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}" class="form-control" placeholder="Email address" required autofocus>
                </div>
                <div class="form-label-group my-3">
                    <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
                </div>
                <button class="btn btn-primary btn-block my-3" type="submit">
                    {% if 'login' in request.path %}
                    ログイン
                    {% elif 'signup' in request.path %}
                    新規登録
                    {% endif %}
                </button>
            </form>

            {% if 'login' in request.path %}
            <div class="text-center">
                <a href="/signup/" class="link-secndary">新規登録はこちら</a>
            </div>
            {% elif 'signup' in request.path %}
            <div class="text-center">
                <a href="/login/" class="link-secndary">ログインはこちら</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{{req}}
{% endblock %}

templates/mysite/base.html
<!doctype html>
<html lang="ja">

<head>
    {% include 'mysite/snippets/head.html' %}
</head>

<body>
    {% include 'mysite/snippets/header.html' %}
    {% include 'mysite/snippets/messages.html' %}

    {% block content %}
    {% endblock %}
    {% include 'mysite/snippets/footer.html' %}
</body>

</html>

templates/mysite/base_auth.html
<!doctype html>
<html lang="ja">
  <head>
        {% include 'mysite/snippets/head.html' %}
  </head>
  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">
    {% include 'mysite/snippets/messages.html' %}
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/mysite/cache_test.html
<!-- cache比較用 -->
計算結果の答え: {{ answer }}

templates/mysite/cache_test_template.html
<!-- テンプレートキャッシュ -->
{% load cache %}

<p>キャッシュなし {{time}}</p>

{% cache 10 first_cache %}
<p>キャッシュあり {{time}}</p>
{% endcache %}

{% cache 30 first_cache name %}
<p>キャッシュあり 分岐(ユーザごと等) {{time}}</p>
{% endcache %}

templates/mysite/contact.html
{% extends 'mysite/base.html' %}

{% block content %}
<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            お問いわせ
        </h3>

        <form class="row g-3" method="POST">
            {% csrf_token %}
            <div class="col-12">
                <label class="form-label">名前</label>
                <input type="text" class="form-control" id="id_name" name="name" required>
            </div>
            <div class="col-12">
              <label class="form-label">メールドレス</label>
              <input type="email" class="form-control" id="id_email" name="email" required>
            </div>
            <div class="col-12">
              <label class="form-label">お問い合わせ内容</label>
              <textarea class="form-control" name="content" rows="4" required></textarea>
            </div>

            {% include 'mysite/snippets/recaptcha.html' %}

            <div class="col-12">
              <button type="submit" class="btn btn-primary" id="submit" disabled>送信</button>
            </div>
        </form>
        {% include 'mysite/snippets/sidebar.html' %}
    </div>
</main>


{% endblock %}

templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% block content %}

<div class="container">

    <div class="p-4 p-md-5 mb-4 rounded bg-warning">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Django講座</h1>
            <p class="lead my-3">文章をかこうツ</p>
        </div>
    </div>

    <div class="row mb-2">
        {% for rank in ranks %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row
            mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">
                        {% for tag in rank.tags.all %}
                            {{ tag.name }}
                        {% endfor %}
                    </strong>
                    <h3 class="mb-0">{{rank.title}}</h3>
                    <div class="mb-1 text-muted">
                        {{ rank.created_at }}
                        <div class="d-inline-block text-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="16" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                            </svg>
                            {{ rank.count }}
                        </div>
                    </div>
                    <p class="card-text mb-auto">{{ rank.text }}</p>
                    <!-- stretched-linkでカード自体押下で遷移できる -->
                    <a href="/blog/{{rank.id}}" class="stretched-link"></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                Django Lesson
            </h3>
            <div>{{ articles.0.title }}</div>
            for始まり:
            {% for article in articles %}
                <div class="blog-post">
                    <h2 class="blog-post-title">{{ article.title }}</h2>
                    <p class="blog-post-meta">
                        {{ article.created_at }} by {{ article.author }}
                    </p>
                    <!-- 組み込みテンプレートタグ -->
                    <p>{{ article.text|slice:":19" }}</p>
                    <a href="/blog/{{article.id}}">続きはこちら</a>
                </div>
                <hr>
            {% endfor %}

            <nav class="blog-pagination">
                <a class="btn btn-outline-primary" href="/blog/">ブログ一覧はこちら</a>
            </nav>
        </div>

        {% include 'mysite/snippets/sidebar.html' %}
    </div>
</main>
{% endblock %}

templates/mysite/mypage.html
{% extends 'mysite/base.html' %}

{% block content %}
<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            マイページ
        </h3>

        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'mysite/snippets/profile_image.html' %}

            <div class="col-12">
                <label class="form-label">ユーザー名（公開されます）</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="煉獄 杏寿郎" value="{{user.profile.username}}">
              </div>

              <div class="col-md-2">
                <label class="form-label">郵便番号</label>
                <input type="text" class="form-control" id="id_zipcode" name="zipcode" value="{{user.profile.zipcode}}">
              </div>
              <div class="col-md-4">
                <label class="form-label">都道府県</label>
                <select id="id_prefecture" name="prefecture" class="form-select">
                  <option selected>選択...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="col-md-6">
                <label class="form-label">市区</label>
                <input type="text" class="form-control" id="id_city" name="city" value="{{user.profile.city}}">
              </div>

            <div class="col-12">
              <label class="form-label">住所</label>
              <input type="text" class="form-control" id="id_address" name="address" placeholder="" value="{{user.profile.address}}">
            </div>

            <div class="col-12">
              <button type="submit" class="btn btn-success">保存</button>
            </div>
          </form>

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>
</main>


{% endblock %}

templates/mysite/pay.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                決済 DEMO
            </h3>
        </div>
        {% if charge %}
        chargeの中身: {{charge}}
        <!--
        chargeの中身:
        {
            "amount": 1000,
            "amount_refunded": 0,
            "captured": true,
            "captured_at": 1714726043,
            "card": {
                "address_city": null,
                "address_line1": null,
                "address_line2": null,
                "address_state": null,
                "address_zip": null,
                "address_zip_check": "unchecked",
                "brand": "Visa",
                "country": null,
                "created": 1714726041,
                "customer": "cus_3966251d81e67d7076f4a95d798a",
                "cvc_check": "passed",
                "exp_month": 12,
                "exp_year": 2025,
                "fingerprint": "e1d8225886e3a7211127df751c86787f",
                "id": "car_0cffa4e8c7b43e1d5756bf298864",
                "last4": "4242",
                "livemode": false,
                "metadata": {},
                "name": "PAY TARO",
                "object": "card",
                "three_d_secure_status": null
            },
            "created": 1714726043,
            "currency": "jpy",
            "customer": "cus_3966251d81e67d7076f4a95d798a",
            "description": "\u652f\u6255\u3044\u30c6\u30b9\u30c8",
            "expired_at": null,
            "failure_code": null,
            "failure_message": null,
            "fee_rate": "3.00",
            "id": "ch_1cad61a262a062dd248b89e096e88",
            "livemode": false,
            "metadata": {},
            "object": "charge",
            "paid": true,
            "refund_reason": null,
            "refunded": false,
            "subscription": null,
            "term_id": null,
            "three_d_secure_status": null
        }
        -->
        {% endif %}
        <form method="post">
            {% csrf_token %}

            <script
                type="text/javascript"
                src="https://checkout.pay.jp"
                class="payjp-button"
                data-key="{{ public_key }}">
            </script>

        </form>
        {% include 'mysite/snippets/sidebar.html' %}
    </div>
</main>
{% endblock %}